### ISSUE TITLE
News screentask?

### ISSUE THREAD

**Issue by manuelsongokuh** [ahmadomar/ScreenTask#2]
Alive or dead this project?

**Comment by ahmadomar** [comment]
Alive :)

**Comment by manuelsongokuh** [comment]
ok, there is news for roadmap..?
i wish.. check fps from A pc to B pc fps will be same?
like ask status monitoring (fps, bit send, byte send, signal network..) this is optional for check/testing..

**Comment by HoffmannP** [comment]
Let's merge
