### ISSUE TITLE
Graybar in java version on Win7

### ISSUE THREAD

**Issue by philguimond** [ahmadomar/ScreenTask#8]
Hello @ahmadomar,

I have no choice but to use the Java version on Win7 because the c# line "HTTPServer.start()" is not working if you don't have admin rights (I tried without any firewall/antivirus/netsh url reservation....) nothing worked... anyway I clearly have something blocking it but this isn't the main issue)

The Java issue is the rate at which the new images are being buffered. In other words, I'm getting gray bars every few seconds when watching someone else's screen share. The gray bars are there like half a seconds every once in a while. I don't know if you have any idea on how to increase the rate at which java save an image.

**Comment by philguimond** [comment]
You can actually fix this java issue by changing the write format in the ScreenShot.java class. Changing from jpg to bmp did the trick for me

**Comment by paul-kline** [comment]
changing to bmp made it worse for me as in the entire image disappears from the webpage occasionally. Any other ideas?

**Comment by paul-kline** [comment]
A friend helped me make a fix. Write to a temp file instead of the main file, then just copy the file to the correct location once the write is complete. Grey screen completely gone for me!
In ScreenShot.java:

```

String fileNameToSaveTo = startDir+"/WebServer/ScreenTask.jpg";
        String tempName = startDir+"/WebServer/ScreenTasktmp.jpg" ;
        /**
         * Write the captured image to a file.
         */
        File tmp = new File(tempName);
        ImageIO.write(screenCapture, "jpg",tmp );
        tmp.renameTo(new File(fileNameToSaveTo));
```

**Comment by Tecnico1931** [comment]
@paul-kline Can you share a copy of your build ?

**Comment by paul-kline** [comment]
Certainly @Tecnico1931 ! Here is my forked build: [https://github.com/paul-kline/ScreenTask](https://github.com/paul-kline/ScreenTask) 

This version also allows you to select (on the fly) which screen you would like to share :)

Let me know if there are any issue with it. I had abandoned it for a long time and just tried to make some changes today to make it work so I could share. 

NOTE:  To run it, you cannot simply run the jar in the dist.  The jar _has_ to be located in the same directory as the folder called WebServer (see photo) 
![image](https://user-images.githubusercontent.com/2263842/30712323-4a2f5794-9ed1-11e7-875f-1abf20f4ea24.png)

I have included this folder at the top level of my git. It contains the files expected to be found by the jar. 

quick start:
1. clone or download zip repo (and unzip)
2. move the jar in the dist dir up one directory.
3. run it.

**Comment by Tecnico1931** [comment]
@paul-kline getting this error:
Starting Server, Please Wait...
Permission denied
An error while starting the server

**Comment by paul-kline** [comment]
must be run as admin (maybe just the first time?). I don't know a better way on windows other than:
windows start --> type "powershell"
right click --> run as administrator
cd PATHTOJAR
java -jar ScreenTask.jar

**Comment by Tecnico1931** [comment]
@paul-kline 
Open when I sudo but:

java.io.FileNotFoundException: /Users/raul/Downloads/ScreenTask-master%203/ScreenTaskGeneric/WebServer/ScreenTasktmp.jpg (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
	at javax.imageio.ImageIO.write(ImageIO.java:1530)
	at screentask.ScreenShot.takeScreenshot(ScreenShot.java:89)
	at screentask.ScreenThread.run(ScreenThread.java:30)
Sep 21, 2017 2:49:56 PM screentask.ScreenThread run
SEVERE: null
java.lang.NullPointerException
	at javax.imageio.ImageIO.write(ImageIO.java:1538)
	at screentask.ScreenShot.takeScreenshot(ScreenShot.java:89)
	at screentask.ScreenThread.run(ScreenThread.java:30)

**Comment by paul-kline** [comment]
hmm. What is your OS?
Try creating the file it's complaining about (.../WebServer/ScreenTasktmp.jpg) and let know what it says

**Comment by paul-kline** [comment]
updated the top level WebServer dir to included the needed files. git pull. @Tecnico1931

**Comment by Tecnico1931** [comment]
@paul-kline after creating ScreenTasktmp.jpg it's working on Mac OS but must run as admin every time.
